# Change these first
owner: RitsuProject # Your GitHub username
repo: themes-status # Your Github repository name

# Add your sites here
sites:
  - name: AnimeThemes
    url: https://animethemes.moe
  - name: AnimeThemes API
    url: https://animethemes.dev
  - name: Openings.moe
    url: https://openings.moe/
  - name: Catbox
    url: https://catbox.moe/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ritsu's Themes Status
  introTitle: "Intro"
  introMessage: Track the status of anime theme repositories like AnimeThemes, Catbox and Openings.moe
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
