# Change these first
owner: RitsuProject # Your GitHub username
repo: ritsu-status # Your Github repository name

# Add your sites here
sites:
  - name: AnimeThemes
    url: https://animethemes.moe
  - name: AnimeThemes API
    url: https://staging.animethemes.moe
  - name: Ritsu API
    url: https://api.ritsu.fun/network
  - name: Openings.moe
    url: https://openings.moe/
  - name: Catbox
    url: https://catbox.moe/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.sazz.fail
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ritsu's Status
  introTitle: "wtf is this"
  introMessage: This website tracks the status of sites that are usually repositories of anime openings/endings themes, such as AnimeThemes, Openings.moe, Catbox and Ritsu itself.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: discord

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
